# Generated by Django 4.2.5 on 2023-12-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_moderatorrightsrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderatorrightsrequest',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтверждение запроса'),
        ),
    ]
